import { type LatLng } from "./geo";

export type DirectoryTurf = {
  id: string;
  name: string;
  area: string;
  address: string;
  pin: LatLng;
  /** Neighbourhood-level pin unless a listing published exact coords. */
  pinPrecision: "exact" | "neighbourhood";
  phone: string;
  sports: string[];
  hours: string;
  priceFromInr: number | null;
  pitches: number | null;
  notes: string;
  matchKeys: string[];
  /** Set when this listing is the seeded Turf Community venue. */
  communitySlug?: string;
};

function key(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

/**
 * Public Vadodara turf, box-cricket and pickleball directory, compiled
 * August 2026 from TurfBooking, Hudle, Justdial, CricketGround, KheloMore,
 * Playo, venue sites and Instagram. Phones and rates change — Call / Visit
 * before you drive.
 */
export const VADODARA_TURFS: DirectoryTurf[] = [
  {
    id: "greenfield-arena",
    name: "Greenfield Arena",
    area: "Alkapuri",
    address: "Alkapuri, Vadodara, Gujarat",
    pin: { lat: 22.3132, lng: 73.1718 },
    pinPrecision: "neighbourhood",
    phone: "9876543210",
    sports: ["5-a-side football"],
    hours: "06:00 – 23:00 IST",
    priceFromInr: 900,
    pitches: 2,
    notes: "Floodlit 5-a-side. Pay UPI before confirmation. Arrive 10 minutes early.",
    matchKeys: ["greenfieldarena", "greenfield"],
    communitySlug: "demo",
  },
  {
    id: "united-sports-arena",
    name: "United Sports Arena",
    area: "Manjalpur",
    address: "Beside Patanjali Store, Amarnath Puram Society, Shivam Society, Manjalpur, Vadodara",
    pin: { lat: 22.27052, lng: 73.18686 },
    pinPrecision: "neighbourhood",
    phone: "9016835490",
    sports: ["7-a-side football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 550,
    pitches: null,
    notes: "Listed from ₹550/hr on Hudle, ₹1,300/hr on TurfBooking.",
    matchKeys: ["unitedsportsarena", "unitedsports"],
  },
  {
    id: "goat-turf",
    name: "G.O.A.T Turf",
    area: "Makarpura GIDC",
    address: "Plot 74 & 77/3, VCCI Sports Complex, GIDC Rd, Industrial Bank, Makarpura GIDC, Vadodara 390010",
    pin: { lat: 22.247, lng: 73.1955 },
    pinPrecision: "neighbourhood",
    phone: "7096111818",
    sports: ["football", "pickleball"],
    hours: "Open 24 hours",
    priceFromInr: 1250,
    pitches: null,
    notes: "Marketed as Vadodara’s first 24×7 turf.",
    matchKeys: ["goatturf", "greatestofallturfs", "goat"],
  },
  {
    id: "big-shot",
    name: "The Big Shot Turf",
    area: "Tarsali",
    address: "NH 48, Adarsh Nagar, opposite Legend Hotel, near Dhaniyavi / Tarsali chokdi, Vadodara 390009",
    pin: { lat: 22.2574, lng: 73.2212 },
    pinPrecision: "neighbourhood",
    phone: "9238764656",
    sports: ["football", "box cricket"],
    hours: "Call for hours",
    priceFromInr: 1250,
    pitches: 3,
    notes: "Cafe on site. TurfBooking lists three pitches.",
    matchKeys: ["thebigshotturf", "bigshotturf", "bigshot"],
  },
  {
    id: "turf-terra",
    name: "The Turf Terra (T3)",
    area: "Sevasi",
    address: "Gotri–Sevasi Road, beside Greenwoods Infinity, near Decathlon, Sevasi, Khanpur, Vadodara 391101",
    pin: { lat: 22.3155, lng: 73.118 },
    pinPrecision: "neighbourhood",
    phone: "8320746692",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Open 24 hours",
    priceFromInr: 999,
    pitches: 2,
    notes: "Listed size 145 × 120 ft. Second number 83203 92179.",
    matchKeys: ["theturfterra", "turfterra", "t3"],
  },
  {
    id: "ballers-turf",
    name: "Baller's Turf",
    area: "Gotri",
    address: "Prince and Princess Villa, Gotri–Sevasi Road, behind Collabera Call Center, Chandramauleshwar Nagar, Gotri, Vadodara 390021",
    pin: { lat: 22.3218, lng: 73.1465 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["football", "pickleball"],
    hours: "06:00 – 00:00",
    priceFromInr: null,
    pitches: null,
    notes: "Also listed behind Shaishav School on Gotri–Sevasi Main Road. No public booking number found — use Visit.",
    matchKeys: ["ballersturf", "ballersturfgotri"],
  },
  {
    id: "athletes-arena",
    name: "Athlete's Arena",
    area: "Sevasi",
    address: "FF 99, behind Jalsa Apartments, Priya Talkies Road, near Adventuraa Park, Sevasi, Vadodara 391101",
    pin: { lat: 22.314, lng: 73.122 },
    pinPrecision: "neighbourhood",
    phone: "9371003838",
    sports: ["7-a-side football", "box cricket", "pickleball", "padel"],
    hours: "Open 24 hours",
    priceFromInr: 225,
    pitches: null,
    notes: "7v7 turf plus padel and two pickleball courts. Alt. 82081 54349 / 81605 43907.",
    matchKeys: ["athletesarena", "athletearena"],
  },
  {
    id: "turf-08",
    name: "TURF 08",
    area: "Mahapura",
    address: "Near Stonebrook, Mahapura, Vadodara 391101",
    pin: { lat: 22.3109822, lng: 73.1095577 },
    pinPrecision: "exact",
    phone: "9687423858",
    sports: ["football", "box cricket"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "West Vadodara, Sevasi–Sindhrot belt.",
    matchKeys: ["turf08", "truf08"],
  },
  {
    id: "fc-arena-park",
    name: "FC Arena Park",
    area: "Manjalpur",
    address: "75FF+X8, Manjalpur, Vadodara 390011",
    pin: { lat: 22.2738, lng: 73.1885 },
    pinPrecision: "neighbourhood",
    phone: "9213454312",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "Separate from FC Arena 360 in Vadsar.",
    matchKeys: ["fcarenapark", "fcarena", "fcarenavadodara"],
  },
  {
    id: "fc-arena-360",
    name: "FC Arena 360",
    area: "Vadsar / Kalali",
    address: "7559+RP, near Vadsar bridge, Kalali, Vadodara 390012",
    pin: { lat: 22.262, lng: 73.1485 },
    pinPrecision: "neighbourhood",
    phone: "9974844040",
    sports: ["football", "box cricket"],
    hours: "Open 24 hours",
    priceFromInr: 600,
    pitches: null,
    notes: "Round turf. KheloMore from ₹600/hr.",
    matchKeys: ["fcarena360"],
  },
  {
    id: "sportingo",
    name: "Sportingo Football Turf & Box Cricket",
    area: "Manjalpur",
    address: "Manjalpur, Vadodara",
    pin: { lat: 22.27052, lng: 73.18686 },
    pinPrecision: "neighbourhood",
    phone: "7965211665",
    sports: ["football", "box cricket", "badminton", "padel", "pickleball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "Multi-sport. Confirm the gate on the map pin before you go.",
    matchKeys: ["sportingo"],
  },
  {
    id: "amodar",
    name: "Amodar Box Cricket & Football Turf",
    area: "Waghodia Road",
    address: "Shivam Farms, near Amodar Bus Stop, opp. Prime Plaza, Waghodia, Vadodara 390019",
    pin: { lat: 22.2936256, lng: 73.2957929 },
    pinPrecision: "exact",
    phone: "9925036755",
    sports: ["football", "box cricket"],
    hours: "Open 24 hours",
    priceFromInr: 1200,
    pitches: 2,
    notes: "East of the city on Waghodia Road.",
    matchKeys: ["amodar", "amodarboxcricket"],
  },
  {
    id: "turf-73",
    name: "TURF 73",
    area: "Kishanwadi",
    address: "New VIP Road, beside Earth Icon, near 30 m Khodiyar Nagar Road, Purushottam Nagar, Kishanwadi, Vadodara 390019",
    pin: { lat: 22.3275, lng: 73.218 },
    pinPrecision: "neighbourhood",
    phone: "9737338700",
    sports: ["football", "box cricket"],
    hours: "Call for hours",
    priceFromInr: 1200,
    pitches: null,
    notes: "Ajwa / New VIP Road belt.",
    matchKeys: ["turf73"],
  },
  {
    id: "infinity-turf",
    name: "Infinity Turf (D Turf)",
    area: "Waghodia",
    address: "Opp. Parul University, Ishwarpura Road, near Bajrang Food Zone, Waghodia, Vadodara 391760",
    pin: { lat: 22.3085, lng: 73.363 },
    pinPrecision: "neighbourhood",
    phone: "9998124007",
    sports: ["football", "box cricket"],
    hours: "Open 24 hours",
    priceFromInr: 1200,
    pitches: null,
    notes: "Also listed as D Turf. Alt. 87809 43411 / 90166 58360.",
    matchKeys: ["infinityturf", "dturf"],
  },
  {
    id: "troopers",
    name: "Troopers",
    area: "Chhani",
    address: "Chhani–Sokhda Road, behind Narayan Tirth Bungalows, opp. Dwarkesh Bungalows, near Chhani Lake, Vadodara 391740",
    pin: { lat: 22.3680326, lng: 73.1705445 },
    pinPrecision: "exact",
    phone: "",
    sports: ["football", "box cricket"],
    hours: "Call for hours",
    priceFromInr: 1300,
    pitches: null,
    notes: "No public phone in directories — open Visit for the gate.",
    matchKeys: ["troopers", "troopersboxcricket"],
  },
  {
    id: "huddle-karelibaug",
    name: "Huddle Arena — Karelibaug",
    area: "Karelibaug",
    address: "Sayajibaug Road, opposite Kashiben Children Hospital, near Bal Bhavan, Karelibaug, Vadodara 390018",
    pin: { lat: 22.3188, lng: 73.1985 },
    pinPrecision: "neighbourhood",
    phone: "7227890349",
    sports: ["football", "box cricket", "volleyball", "pickleball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "One of three Huddle grounds in the city.",
    matchKeys: ["huddlearena", "huddle", "huddlesportsarena"],
  },
  {
    id: "huddle-vasna",
    name: "Huddle Arena — Vasna–Bhayli",
    area: "Vasna–Bhayli",
    address: "Besides Pincode 55, opp. Darshanam Splendora, Vasna–Bhayli Main Road, Vadodara 390007",
    pin: { lat: 22.2955, lng: 73.1285 },
    pinPrecision: "neighbourhood",
    phone: "7227890349",
    sports: ["football", "box cricket", "volleyball", "pickleball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "Same Huddle desk number as Karelibaug.",
    matchKeys: ["huddlearenavasna"],
  },
  {
    id: "huddle-sama",
    name: "Huddle Arena — Sama",
    area: "Sama / Vemali",
    address: "Canal Road, behind Shivam Party Plot, New Sama, Vemali, Vadodara 390024",
    pin: { lat: 22.355, lng: 73.195 },
    pinPrecision: "neighbourhood",
    phone: "7227890349",
    sports: ["6-a-side football", "box cricket", "volleyball", "pickleball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "North canal road. Hudle lists pickleball from ₹200.",
    matchKeys: ["huddlearenasama"],
  },
  {
    id: "juggernaut",
    name: "Juggernaut Arena",
    area: "Bhayli",
    address: "Behind Bright Day School, off Vasna–Bhayli Main Road, near Vihaan Hospital, Bhayli, Vadodara",
    pin: { lat: 22.288, lng: 73.122 },
    pinPrecision: "neighbourhood",
    phone: "9979114941",
    sports: ["football", "box cricket"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "FIFA-preferred turf listing. Alt. 77909 63789.",
    matchKeys: ["juggernaut", "juggernautarena"],
  },
  {
    id: "yagnik",
    name: "Yagnik Sports Academy",
    area: "Chhani / Sama",
    address: "Yagnik Vidyalaya Campus, Chhani–Sama Canal Road, Vadodara 390002",
    pin: { lat: 22.345, lng: 73.185 },
    pinPrecision: "neighbourhood",
    phone: "9586228840",
    sports: ["football", "cricket", "pickleball", "basketball"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "Academy ground — also a second listing at VCA Sevasi Canal Road, Bhayli (95377 31616).",
    matchKeys: ["yagniksportsacademy", "yagniksportacademy"],
  },
  {
    id: "turf-99",
    name: "Turf 99",
    area: "Harni",
    address: "Near Krishnam Airwings, behind P.G. Banquet & Lawns, Mothnath Circle, Harni, Vadodara 390022",
    pin: { lat: 22.3365, lng: 73.2135 },
    pinPrecision: "neighbourhood",
    phone: "7740878408",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 400,
    pitches: null,
    notes: "Covered dome turf. Pickleball from ₹400/hr on Hudle.",
    matchKeys: ["turf99", "turff99"],
  },
  {
    id: "sports-arena-box",
    name: "Sports Arena Box Cricket",
    area: "Bakrol / Ajwa",
    address: "Beside Sigma University, Hanumanpura Village, Ajwa Road, Bakrol, Vadodara 390019",
    pin: { lat: 22.328, lng: 73.258 },
    pinPrecision: "neighbourhood",
    phone: "8128816887",
    sports: ["box cricket", "football"],
    hours: "07:00 – 00:00",
    priceFromInr: 900,
    pitches: null,
    notes: "Day from ₹900, night from ₹1,300. Alt. 96385 13395.",
    matchKeys: ["sportsarenaboxcricket", "sportsarenabakrol"],
  },
  {
    id: "hp-369",
    name: "HP 369 Box Cricket",
    area: "Ratanpur / Kapurai",
    address: "Dabohi Road, behind Krishna Hotel, 2 km from Kapurai chokdi, Ratanpur, Vadodara 390004",
    pin: { lat: 22.2581386, lng: 73.2549557 },
    pinPrecision: "exact",
    phone: "8401750369",
    sports: ["box cricket"],
    hours: "Open 24 hours",
    priceFromInr: null,
    pitches: null,
    notes: "South-east of the city on Dabohi Road.",
    matchKeys: ["hp369", "hp369boxcricket"],
  },
  {
    id: "rough-n-turf",
    name: "Rough N Turf",
    area: "Sevasi",
    address: "Behind Adventuraa Park, near Priya Talkies, Sevasi / Bhayli, Vadodara 391410",
    pin: { lat: 22.314, lng: 73.122 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["box cricket", "football"],
    hours: "Call for hours",
    priceFromInr: null,
    pitches: null,
    notes: "Playo lists this as a Sevasi box-cricket ground. No public phone — use Visit.",
    matchKeys: ["roughnturf", "roughandturf"],
  },
  {
    id: "vff-box",
    name: "VFF Box Cricket",
    area: "Bhayli",
    address: "Beside Sorento Rosset, near Waves Club, Vasna–Bhayli Canal Road, Bhayli, Vadodara 391410",
    pin: { lat: 22.292, lng: 73.125 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["box cricket"],
    hours: "06:00 – 01:00",
    priceFromInr: null,
    pitches: null,
    notes: "No public booking number in directories — open Visit for the gate.",
    matchKeys: ["vffboxcricket", "vff"],
  },
  {
    id: "urban-turf",
    name: "Urban Turf by Sports Ocean",
    area: "Samiyala",
    address: "Urban Fitness, behind Sai Baba Temple, ahead of Atladara railway crossing & Banco Aluminium, Padra Road, Samiyala, Bhayli, Vadodara 391410",
    pin: { lat: 22.268, lng: 73.108 },
    pinPrecision: "neighbourhood",
    phone: "9213563747",
    sports: ["8-a-side football", "box cricket", "volleyball"],
    hours: "Open 24 hours",
    priceFromInr: 499,
    pitches: null,
    notes: "One of the larger Padra Road turfs. Hudle from ₹250 volleyball / ₹500 turf.",
    matchKeys: ["urbanturf", "urbanturfbysportsocean", "sportsocean"],
  },
  {
    id: "strikers",
    name: "Strikers Game Arena",
    area: "Atladara",
    address: "Atladara Lake Road, Phoenix School Road, Narayanwadi, Atladara, Vadodara",
    pin: { lat: 22.272, lng: 73.148 },
    pinPrecision: "neighbourhood",
    phone: "6352165706",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 600,
    pitches: null,
    notes: "8v8 football / box cricket around ₹1,500; pickleball from ₹600 on Hudle.",
    matchKeys: ["strikersgamearena", "strikers"],
  },
  {
    id: "hattrick",
    name: "Hattrick Turf & Pickleball Arena",
    area: "Chhani",
    address: "Canal Road, Amardeep Villa / Neelam Farm belt, Chhani, Vadodara",
    pin: { lat: 22.365, lng: 73.172 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 300,
    pitches: null,
    notes: "Hudle pickleball from ₹300. Confirm the canal-road gate on the map.",
    matchKeys: ["hattrickturf", "hattrickpickleball"],
  },
  {
    id: "kavish-turf-7",
    name: "Kavish Pickleball & Turf 7",
    area: "Harni",
    address: "Kavish Cafe, NH-8, opposite RTO Darjipura, near Golden Chowkadi, Harni, Vadodara 390022",
    pin: { lat: 22.342, lng: 73.228 },
    pinPrecision: "neighbourhood",
    phone: "9726287245",
    sports: ["6-a-side football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 200,
    pitches: null,
    notes: "Hudle: 6v6 football / cricket from ₹400, pickleball from ₹200.",
    matchKeys: ["kavishpickleball", "kavishturf7", "turf7"],
  },
  {
    id: "hercules",
    name: "Hercules Sports Arena",
    area: "Bhayli",
    address: "Behind Pragati High School, beside Ashoka Residency, Bhayli, Vadodara 391410",
    pin: { lat: 22.288, lng: 73.118 },
    pinPrecision: "neighbourhood",
    phone: "9974944041",
    sports: ["box cricket", "football", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 200,
    pitches: null,
    notes: "Round cricket turf. Alt. 93278 41149. Pickleball from ₹200 on Hudle.",
    matchKeys: ["herculessportsarena", "herculescricketarena"],
  },
  {
    id: "fc-arena-bhayli",
    name: "FC Arena Bhayli",
    area: "Bhayli",
    address: "Opposite Darshanam Splendora, Vasant Vihar, Vasna–Bhayli Road, Vadodara 391410",
    pin: { lat: 22.2955, lng: 73.1285 },
    pinPrecision: "neighbourhood",
    phone: "9213454312",
    sports: ["football", "box cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 550,
    pitches: null,
    notes: "Same desk as FC Arena Park in Manjalpur — different ground. Pickleball from ₹550.",
    matchKeys: ["fcarenabhayli", "fcarenavasnabhayli"],
  },
  {
    id: "blaze-turf",
    name: "Blaze Turf",
    area: "Bhayli",
    address: "Opposite Kalash Elite / Seasons Prime, Bhayli Road, Vadodara 391410",
    pin: { lat: 22.29, lng: 73.125 },
    pinPrecision: "neighbourhood",
    phone: "8866382202",
    sports: ["football", "box cricket", "pickleball"],
    hours: "06:00 – 00:00",
    priceFromInr: 399,
    pitches: null,
    notes: "Turf around ₹1,100; pickleball from ₹399. Alt. 91066 76774.",
    matchKeys: ["blazeturf", "blazeturfcafe"],
  },
  {
    id: "sports-77",
    name: "77 Sports Arena",
    area: "Bhayli",
    address: "Opposite Ashoka Apartment, Bhayli, Vasna, Vadodara 391410",
    pin: { lat: 22.289, lng: 73.12 },
    pinPrecision: "neighbourhood",
    phone: "9979733048",
    sports: ["football", "box cricket"],
    hours: "06:00 – 02:00",
    priceFromInr: 150,
    pitches: null,
    notes: "KheloMore from ₹150. Confirm the Ashoka Apartment gate.",
    matchKeys: ["77sportsarena", "77sports"],
  },
  {
    id: "jsi-arena",
    name: "JSI Sports Arena",
    area: "Bhayli",
    address: "Vibgyor High School, Padra Road, Bhayli, Vadodara 391410",
    pin: { lat: 22.285, lng: 73.115 },
    pinPrecision: "neighbourhood",
    phone: "8828117187",
    sports: ["box cricket", "football"],
    hours: "17:00 – 23:00",
    priceFromInr: 1000,
    pitches: null,
    notes: "On the Vibgyor campus. Evening slots.",
    matchKeys: ["jsisportsarena", "jsiarena"],
  },
  {
    id: "advick",
    name: "Advick Sports Club",
    area: "Vemali",
    address: "Near Aaradhya Sunshine, Vemali, Vadodara",
    pin: { lat: 22.358, lng: 73.19 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["box cricket", "cricket", "pickleball"],
    hours: "Call for hours",
    priceFromInr: 500,
    pitches: null,
    notes: "Hudle: natural-grass 6v6 box cricket from ₹1,250, pickleball from ₹500.",
    matchKeys: ["advicksportsclub", "advick"],
  },
  {
    id: "vadodara-pickleball-arena",
    name: "Vadodara Pickleball Arena",
    area: "OP Road",
    address: "Plot 19, JP Nagar, beside Sera Pizzeria, next to GEB Colony, opposite Hanuman Mandir, Old Padra / OP Road, Vadodara 390015",
    pin: { lat: 22.2977718, lng: 73.1647901 },
    pinPrecision: "exact",
    phone: "9974191811",
    sports: ["pickleball"],
    hours: "Open till 01:00",
    priceFromInr: 400,
    pitches: 3,
    notes: "Three synthetic courts. Open till 1am.",
    matchKeys: ["vadodarapickleballarena", "vpa"],
  },
  {
    id: "3rd-shot",
    name: "3rd Shot by Strokess",
    area: "Ankodiya",
    address: "Opposite Eclipse Sports 2, New Alkapuri, Ankodiya, Vadodara 391330",
    pin: { lat: 22.3359325, lng: 73.1217361 },
    pinPrecision: "exact",
    phone: "9316556659",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 500,
    pitches: 8,
    notes: "Eight synthetic courts. Coaching and DUPR nights.",
    matchKeys: ["3rdshot", "3rdshotbystrokess", "strokess"],
  },
  {
    id: "communex",
    name: "CommuneX Pickleball",
    area: "Sevasi Canal Road",
    address: "Sevasi Canal Road, near Vadodara Cricket Academy, behind Samnvay Westbank, Gotri / Sevasi, Vadodara 391101",
    pin: { lat: 22.318, lng: 73.122 },
    pinPrecision: "neighbourhood",
    phone: "9723454939",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 600,
    pitches: 6,
    notes: "Six outdoor courts on the canal road.",
    matchKeys: ["communex", "communexpickleball"],
  },
  {
    id: "elite-sky",
    name: "Elite Sky Pickleball",
    area: "Tandalja",
    address: "2nd floor rooftop, Pavitra Landmark, Vasna–Bhayli Main Road, opposite Panchmukhi Hanuman Mandir, Ashwamegh Nagar, Tandalja, Vadodara 391410",
    pin: { lat: 22.291, lng: 73.145 },
    pinPrecision: "neighbourhood",
    phone: "8401288997",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 600,
    pitches: null,
    notes: "Rooftop courts.",
    matchKeys: ["eliteskypickleball", "elitesky"],
  },
  {
    id: "homeground",
    name: "Homeground",
    area: "Sevasi",
    address: "Aark International School, Bhayali Ring Road, opposite Samay Party Plot, TP1, Sevasi, Vadodara",
    pin: { lat: 22.312, lng: 73.115 },
    pinPrecision: "neighbourhood",
    phone: "9638360455",
    sports: ["pickleball", "padel"],
    hours: "Call for hours",
    priceFromInr: 450,
    pitches: 3,
    notes: "Two padel courts (from ₹1,000) and three pickleball courts.",
    matchKeys: ["homeground", "homegroundvadodara"],
  },
  {
    id: "t3-rooftop-harni",
    name: "T3 Rooftop Pickleball Club",
    area: "Harni",
    address: "10th floor terrace, The Iconic, 30 mtr Status Road, opposite The Landmark, Harni, Vadodara 390022",
    pin: { lat: 22.338, lng: 73.216 },
    pinPrecision: "neighbourhood",
    phone: "9979270831",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 200,
    pitches: 2,
    notes: "Separate from The Turf Terra (T3) in Sevasi. Two rooftop courts.",
    matchKeys: ["t3rooftop", "t3rooftoppickleball", "t3harni"],
  },
  {
    id: "vintage-pickleball",
    name: "Vintage Pickleball",
    area: "Harni",
    address: "Vintage Valley Restaurant, Airport Road, near Gada Circle, Harni, Vadodara",
    pin: { lat: 22.34, lng: 73.21 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 175,
    pitches: 3,
    notes: "Three outdoor courts. Hudle from ₹175.",
    matchKeys: ["vintagepickleball"],
  },
  {
    id: "net-ninjas",
    name: "Net Ninjas Pickleball",
    area: "Harni",
    address: "Rajeshwar Gold View, opposite Rajeshwar Shopping Market, Harni, Vadodara 390022",
    pin: { lat: 22.337, lng: 73.214 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 250,
    pitches: null,
    notes: "Hudle from ₹250.",
    matchKeys: ["netninjas", "netninjaspickleball"],
  },
  {
    id: "h3k",
    name: "H3K Pickleball House & Cafe",
    area: "Sevasi",
    address: "Artistry Cafe, Sevasi–Sindhrot Road, Sevasi, Vadodara",
    pin: { lat: 22.316, lng: 73.108 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 400,
    pitches: null,
    notes: "Cafe on site. Hudle from ₹400.",
    matchKeys: ["h3k", "h3kpickleball"],
  },
  {
    id: "house-of-pickleball",
    name: "House of Pickleball",
    area: "New Alkapuri",
    address: "Beside Shivaay Farm & Banquet, Ankodiya Road, New Alkapuri, Vadodara",
    pin: { lat: 22.334, lng: 73.124 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 700,
    pitches: 8,
    notes: "Indoor and AC indoor courts. Hudle AC from ₹1,200, indoor from ₹700.",
    matchKeys: ["houseofpickleball"],
  },
  {
    id: "smash-pickleball",
    name: "Smash Pickleball Club & Cafe",
    area: "Saiyed Vasna",
    address: "Beside Dojo Fitness MMA, behind Kalyan Party Plot, Vasna–Bhayli Main Road, Krishnadham Society, Saiyed Vasna, Vadodara 390007",
    pin: { lat: 22.293, lng: 73.145 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 600,
    pitches: 4,
    notes: "Four outdoor courts.",
    matchKeys: ["smashpickleball", "smashpickleballclub"],
  },
  {
    id: "fc-smash",
    name: "FC Smash Pickleball",
    area: "New Manjalpur",
    address: "New Manjalpur, Vadodara",
    pin: { lat: 22.268, lng: 73.192 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 250,
    pitches: null,
    notes: "Hudle from ₹250. Confirm the gate on the map — neighbourhood pin.",
    matchKeys: ["fcsmashpickleball", "fcsmash"],
  },
  {
    id: "united-pickleball",
    name: "United Pickleball",
    area: "Sevasi Canal Road",
    address: "Survey no. 170, Jalsa, 72-2, Sevasi Canal Road, Vadodara",
    pin: { lat: 22.316, lng: 73.12 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "06:00 – 00:00",
    priceFromInr: 500,
    pitches: null,
    notes: "Separate from United Sports Arena in Manjalpur.",
    matchKeys: ["unitedpickleball"],
  },
  {
    id: "pickle-madness",
    name: "Pickle Madness",
    area: "Sevasi",
    address: "Plot 31/9 B, Sevasi Canal Road, next to Pushpak Tennis Academy, near Tarak Bungalows, Sevasi, Vadodara",
    pin: { lat: 22.317, lng: 73.121 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "06:00 – 01:00",
    priceFromInr: 400,
    pitches: null,
    notes: "Hudle from ₹400.",
    matchKeys: ["picklemadness"],
  },
  {
    id: "yardx",
    name: "YardX Courts & Cafe",
    area: "Atladara",
    address: "Bill Kalai Road, near Shastriji Petroleum, beside Evara Greens, Atladara, Vadodara",
    pin: { lat: 22.2735, lng: 73.156 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball", "football"],
    hours: "Call for hours",
    priceFromInr: 650,
    pitches: 3,
    notes: "Three outdoor pickleball courts. Also on Hudle’s football list.",
    matchKeys: ["yardx", "yardxcourts"],
  },
  {
    id: "v16",
    name: "V16 Sports Lounge",
    area: "New Alkapuri",
    address: "The Eclipse Sports-2, V-16, New Alkapuri, Ankodiya, Vadodara 391330",
    pin: { lat: 22.335656, lng: 73.1216484 },
    pinPrecision: "exact",
    phone: "9316689359",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 500,
    pitches: 3,
    notes: "Three courts next to Eclipse Sports 2 — same belt as 3rd Shot.",
    matchKeys: ["v16sportslounge", "v16"],
  },
  {
    id: "matchpoint",
    name: "MatchPoint Vadodara",
    area: "New Alkapuri",
    address: "Veda Lawns, TP Road, New Alkapuri, Vadodara",
    pin: { lat: 22.332, lng: 73.128 },
    pinPrecision: "neighbourhood",
    phone: "9316489526",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 400,
    pitches: 7,
    notes: "Seven hard courts. Coaching on site.",
    matchKeys: ["matchpoint", "matchpointvadodara"],
  },
  {
    id: "pickle-n-brew",
    name: "Pickle N Brew",
    area: "New Alkapuri",
    address: "New Alkapuri, Vadodara",
    pin: { lat: 22.334, lng: 73.125 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 200,
    pitches: null,
    notes: "Hudle from ₹200. Confirm the gate — neighbourhood pin.",
    matchKeys: ["picklenbrew"],
  },
  {
    id: "sky-sports-zone",
    name: "Sky Sports Zone",
    area: "Waghodia chokdi",
    address: "Near Hanuman temple, Waghodia chokdi, Vadodara",
    pin: { lat: 22.27, lng: 73.225 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 200,
    pitches: null,
    notes: "KheloMore from ₹200. Confirm the temple gate on the map.",
    matchKeys: ["skysportszone"],
  },
  {
    id: "pushpak",
    name: "Pushpak Courts & Cafe",
    area: "Sevasi",
    address: "Opposite Sears Tower, Sevasi Canal Road, TP-1, Vadodara 391101",
    pin: { lat: 22.317, lng: 73.12 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball", "tennis"],
    hours: "Call for hours",
    priceFromInr: 500,
    pitches: 4,
    notes: "Four pickleball courts plus a tennis court (from ₹800).",
    matchKeys: ["pushpak", "pushpakcourts", "thepickleballcentre"],
  },
  {
    id: "p90",
    name: "P90 The Pickleball Club",
    area: "Saiyed Vasna",
    address: "20/2, Vasna–Bhayli Main Road, opposite White House, Saiyed Vasna, Vadodara 391410",
    pin: { lat: 22.294, lng: 73.142 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 700,
    pitches: 6,
    notes: "Six courts. Hudle from ₹700.",
    matchKeys: ["p90", "p90pickleball"],
  },
  {
    id: "alkapuri-gymkhana",
    name: "Alkapuri Gymkhana Pickleball",
    area: "Alkapuri",
    address: "Alkapuri Gymkhana, Alkapuri, Vadodara",
    pin: { lat: 22.3132, lng: 73.1718 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 700,
    pitches: null,
    notes: "Club courts. Members and walk-in rules vary — call the desk or visit.",
    matchKeys: ["alkapurigymkhana"],
  },
  {
    id: "elevate-sports",
    name: "Elevate Sports Pickleball",
    area: "New Alkapuri",
    address: "New Alkapuri, Vadodara",
    pin: { lat: 22.333, lng: 73.126 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 275,
    pitches: null,
    notes: "Hudle from ₹275. Confirm the gate — neighbourhood pin.",
    matchKeys: ["elevatesports", "elevatesportspickleball"],
  },
  {
    id: "courtyard-picklebrew",
    name: "Courtyard Picklebrew",
    area: "Bhayli",
    address: "Bhayli, Vadodara",
    pin: { lat: 22.2955, lng: 73.1285 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 700,
    pitches: null,
    notes: "Hudle from ₹700. Confirm the gate — neighbourhood pin.",
    matchKeys: ["courtyardpicklebrew"],
  },
  {
    id: "pickle-pros",
    name: "Pickle Pros",
    area: "Manjalpur",
    address: "Manjalpur, Vadodara",
    pin: { lat: 22.27052, lng: 73.18686 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 300,
    pitches: null,
    notes: "Hudle from ₹300. Confirm the gate — neighbourhood pin.",
    matchKeys: ["picklepros"],
  },
  {
    id: "centre-court",
    name: "Centre Court at Torino Social",
    area: "Khanpur",
    address: "Torino Social, behind Bombay Kitchen, Khanpur, Vadodara",
    pin: { lat: 22.312, lng: 73.115 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball", "padel"],
    hours: "Call for hours",
    priceFromInr: 550,
    pitches: null,
    notes: "Social club courts. Hudle from ₹550.",
    matchKeys: ["centrecourt", "centrecourttorino"],
  },
  {
    id: "v-arcade",
    name: "The V Arcade",
    area: "Vivanta",
    address: "Vivanta, Vadodara",
    pin: { lat: 22.315, lng: 73.165 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 500,
    pitches: null,
    notes: "Hudle from ₹500. Confirm the Vivanta gate on the map.",
    matchKeys: ["thevarcade", "varcade"],
  },
  {
    id: "dropshot",
    name: "Dropshot Pickleball Academy & Club",
    area: "Bhayli",
    address: "Plot 334, Navrachna University Road, behind 33LE, opposite Nilamber Grandeur, Bhayli, Vadodara 391410",
    pin: { lat: 22.298, lng: 73.12 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 400,
    pitches: 4,
    notes: "Four synthetic courts.",
    matchKeys: ["dropshot", "dropshotpickleball"],
  },
  {
    id: "alpha-arena",
    name: "Alpha Arena",
    area: "Ellora Park",
    address: "Aaryan Party Plot, next to Atmajyoti Ashram, Ellora Park, Vadodara 390023",
    pin: { lat: 22.318, lng: 73.168 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 400,
    pitches: null,
    notes: "Hudle from ₹400.",
    matchKeys: ["alphaarena"],
  },
  {
    id: "just-pickle",
    name: "Just Pickle",
    area: "Ankodiya",
    address: "Canal Road, near Darshanam King Square, New Alkapuri, Ankodiya, Vadodara",
    pin: { lat: 22.336, lng: 73.12 },
    pinPrecision: "neighbourhood",
    phone: "",
    sports: ["pickleball"],
    hours: "Call for hours",
    priceFromInr: 650,
    pitches: null,
    notes: "Indoor pickleball. Cafe on site (J&J). Hudle from ₹650.",
    matchKeys: ["justpickle", "justpicklevadodara"],
  },
];

export type LiveVenueHint = {
  slug: string;
  name: string;
  city: string;
  area: string;
  phone: string;
  priceInr: number;
  notes: string;
};

export type ListedTurf = DirectoryTurf & {
  onCommunity: boolean;
  slug: string | null;
  livePhone: string;
  livePrice: number | null;
  km: number | null;
};

export type SportFilter = "all" | "community" | "football" | "cricket" | "pickleball";

export function matchesFilter(row: ListedTurf, filter: SportFilter) {
  if (filter === "all") return true;
  if (filter === "community") return row.onCommunity;
  if (filter === "football") {
    return row.sports.some((s) => /football|futsal|5-a-side|6-a-side|7-a-side|8-a-side/i.test(s));
  }
  if (filter === "cricket") return row.sports.some((s) => /cricket/i.test(s));
  if (filter === "pickleball") return row.sports.some((s) => /pickleball/i.test(s));
  return true;
}

export function mergeDirectory(live: LiveVenueHint[], from: LatLng | null): ListedTurf[] {
  const used = new Set<string>();
  const listed: ListedTurf[] = VADODARA_TURFS.map((row) => {
    const hit = live.find((v) => {
      if (row.communitySlug && row.communitySlug === v.slug) return true;
      const nk = key(v.name);
      return nk === key(row.name) || row.matchKeys.includes(nk);
    });
    if (hit) used.add(hit.slug);
    const on = Boolean(hit || row.communitySlug);
    const slug = hit?.slug ?? row.communitySlug ?? null;
    return {
      ...row,
      onCommunity: on,
      slug,
      livePhone: hit?.phone || row.phone,
      livePrice: hit?.priceInr ?? row.priceFromInr,
      km: from ? haversine(from, row.pin) : null,
    };
  });

  for (const v of live) {
    if (used.has(v.slug)) continue;
    if (!/vadodara/i.test(v.city) && v.slug !== "demo") continue;
    const pin = from ?? { lat: 22.310696, lng: 73.192635 };
    listed.push({
      id: `live-${v.slug}`,
      name: v.name,
      area: v.area || v.city,
      address: [v.area, v.city].filter(Boolean).join(", "),
      pin,
      pinPrecision: "neighbourhood",
      phone: v.phone,
      sports: ["5-a-side football"],
      hours: "See booking page",
      priceFromInr: v.priceInr,
      pitches: null,
      notes: v.notes,
      matchKeys: [key(v.name)],
      communitySlug: v.slug,
      onCommunity: true,
      slug: v.slug,
      livePhone: v.phone,
      livePrice: v.priceInr,
      km: from ? haversine(from, pin) : null,
    });
  }

  listed.sort((a, b) => {
    if (a.km != null && b.km != null && a.km !== b.km) return a.km - b.km;
    if (a.onCommunity !== b.onCommunity) return a.onCommunity ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  return listed;
}

function haversine(a: LatLng, b: LatLng) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
}
