/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TurfsRouteImport } from './routes/turfs'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWaWebhookRouteImport } from './routes/api/wa/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TurfsRoute = TurfsRouteImport.update({
  id: '/turfs',
  path: '/turfs',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaWebhookRoute = ApiWaWebhookRouteImport.update({
  id: '/api/wa/webhook',
  path: '/api/wa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/turfs': typeof TurfsRoute
  '/b/$slug': typeof BSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/wa/webhook': typeof ApiWaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/turfs': typeof TurfsRoute
  '/b/$slug': typeof BSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/wa/webhook': typeof ApiWaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/turfs': typeof TurfsRoute
  '/b/$slug': typeof BSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/wa/webhook': typeof ApiWaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/desk'
    | '/learn'
    | '/login'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/turfs'
    | '/b/$slug'
    | '/api/auth/$'
    | '/api/wa/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/desk'
    | '/learn'
    | '/login'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/turfs'
    | '/b/$slug'
    | '/api/auth/$'
    | '/api/wa/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/desk'
    | '/learn'
    | '/login'
    | '/play'
    | '/privacy'
    | '/terms'
    | '/turfs'
    | '/b/$slug'
    | '/api/auth/$'
    | '/api/wa/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DeskRoute: typeof DeskRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TurfsRoute: typeof TurfsRoute
  BSlugRoute: typeof BSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWaWebhookRoute: typeof ApiWaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turfs': {
      id: '/turfs'
      path: '/turfs'
      fullPath: '/turfs'
      preLoaderRoute: typeof TurfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa/webhook': {
      id: '/api/wa/webhook'
      path: '/api/wa/webhook'
      fullPath: '/api/wa/webhook'
      preLoaderRoute: typeof ApiWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DeskRoute: DeskRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TurfsRoute: TurfsRoute,
  BSlugRoute: BSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWaWebhookRoute: ApiWaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
